import type { Metadata } from "next";
import { Geist } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/sonner"

import "./globals.css";
import ProModal from "@/components/general/ProModal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.className} h-full antialiased`}
    >
      <body className="bg-secondary h-full">
        <ClerkProvider>
          <ThemeProvider attribute={"class"} defaultTheme="system" enableSystem>
            <ProModal />
            {children}
          </ThemeProvider>
        </ClerkProvider>
        <Toaster />
      </body>

    </html >
  );
}
